# Generated by Django 4.2.5 on 2023-10-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(blank=True, max_length=20, verbose_name='марка авто')),
                ('manufacturer', models.CharField(blank=True, max_length=20, verbose_name='производитель')),
                ('year', models.IntegerField(blank=True, verbose_name='год')),
                ('gos_number', models.CharField(blank=True, max_length=11, verbose_name='гос номер')),
            ],
        ),
    ]
